### ISSUE TITLE
Getting ccAF to run successfully

### ISSUE THREAD

**Issue by 14zac2** [plaisier-lab/ccAF#2]
Hello!

I am very interested in trying ccAF on my data, but I'm having a few issues getting things started. I've created a virtual environment and installed all dependencies with pip, but I keep running into errors that seem to be related to tensorflow. Right now I am using tensorflow v.2.5 and when I run `predictedLabels = ccAF.ccAF.predict_labels(set1_scanpy)` it gives me the error `AttributeError: module 'tensorflow' has no attribute 'placeholder'`. To solve this, I tried running `import tensorflow.compat.v1 as tf` and `tf.disable_v2_behavior()`, but this did not change the error. I also tried changing to a version of tensorflow < 2, but got different errors and I believe you used tensorflow v2.5 for your work. My environment uses python v3.6.

I also have a couple questions about how to run ccAF, as it wasn't quite clear to me. I am starting from a Seurat object in R, so I have exported this object as a loom file to read into python. In Seurat, I have clustered my data at many different clustering resolutions, and each of these and their associated cluster IDs are saved in the loom file. I would like ccAF to estimate cell cycle stages (particularly quiescent cells) on a per-cluster bases, but I am not sure how I can tell your program which clustering resolution I would like to use.

Finally, I notice that in your test script, you convert gene symbols to Ensembl IDs although you do not mention this in the README file. Is this necessary? I am using a new genome that is not human that I have annotated myself which makes any gene name conversions a bit challenging, so it would be great to understand how exactly the genes need to be labeled for your program to run successfully.

If you could help clarify the above issues, that would be fantastic! I really hope I can get this to work, and really appreciate your time!

**Comment by cplaisier** [comment]
Sorry for the late reply. Yes, we do require the gene ids to be in Ensembl format. We will update that in the Readme, and also provide some additional documentation.

The best suggestion I have for you with the dependency issues is to use the Docker image because it already has all the dependencies met. You can boot that up by installing docker (https://www.docker.com/get-started) and then running the command:

docker run -it -v '<path to scRNA-seq profiles directory>:/files' cplaisier/ccaf

Please let us know if you are still interested and have any other issues.

**Comment by cplaisier** [comment]
Added documentation to say that human Ensembl gene IDs without versions were required to run ccAF, and gave a couple of methods to translated IDs.
